// CommonJS on purpose, same reason as the pet window's preload.cjs --
// Electron preload scripts aren't ES modules even when the package is
// "type": "module".
const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('dash', {
  getData: () => ipcRenderer.invoke('dashboard:get-data'),
  getEdgeVoices: () => ipcRenderer.invoke('dashboard:get-edge-voices'),
  getMimoVoices: () => ipcRenderer.invoke('dashboard:get-mimo-voices'),
  testTtsEngine: (engine) => ipcRenderer.invoke('dashboard:test-tts-engine', engine),
  testSttEngine: (engine) => ipcRenderer.invoke('dashboard:test-stt-engine', engine),
  getTtsFallbackLog: () => ipcRenderer.invoke('dashboard:get-tts-fallback-log'),
  getModels: () => ipcRenderer.invoke('dashboard:models'),
  getReport: (kind) => ipcRenderer.invoke('dashboard:report', kind),
  getReports: () => ipcRenderer.invoke('dashboard:get-reports'),
  deleteReport: (id) => ipcRenderer.invoke('dashboard:delete-report', id),
  getHistory: (day) => ipcRenderer.invoke('dashboard:screentip-history', day),
  getSummary: (day) => ipcRenderer.invoke('dashboard:screentip-summary', day),
  getFocusHeatmap: (days) => ipcRenderer.invoke('dashboard:focus-heatmap', { days }),
  getClaudeUsage: () => ipcRenderer.invoke('dashboard:claude-usage'),
  getPomodoroList: (limit) => ipcRenderer.invoke('dashboard:pomodoro-list', { limit }),

  // Reuses the exact same channels the pet window's own preload sends on --
  // the main-process handlers don't care which window the request came
  // from, they just mutate shared state and persist. The dashboard simply
  // re-fetches getData() itself afterward instead of relying on a push.
  setSetting: (field, value) => ipcRenderer.send('pet:settings-set', { field, value }),
  previewOpacity: (value) => ipcRenderer.send('dashboard:preview-opacity', value),
  setShortcut: (key, accelerator) => ipcRenderer.invoke('dashboard:set-shortcut', { key, accelerator }),
  pickSoundFile: (slot) => ipcRenderer.invoke('dashboard:pick-sound-file', slot),
  clearSoundFile: (slot) => ipcRenderer.invoke('dashboard:clear-sound-file', slot),
  pickBackgroundImage: () => ipcRenderer.invoke('dashboard:pick-background-image'),
  clearBackgroundImage: () => ipcRenderer.invoke('dashboard:clear-background-image'),
  saveCustomTheme: (name) => ipcRenderer.invoke('dashboard:save-custom-theme', { name }),
  renameCustomTheme: (id, name) => ipcRenderer.invoke('dashboard:rename-custom-theme', { id, name }),
  deleteCustomTheme: (id) => ipcRenderer.invoke('dashboard:delete-custom-theme', { id }),
  applyCustomTheme: (id) => ipcRenderer.invoke('dashboard:apply-custom-theme', { id }),
  pickCharacterImages: () => ipcRenderer.invoke('dashboard:pick-character-images'),
  generateCharacterDoc: (payload) => ipcRenderer.invoke('dashboard:generate-character-doc', payload),
  pickPetPackFolder: () => ipcRenderer.invoke('dashboard:pick-pet-pack-folder'),
  commitPetPack: (payload) => ipcRenderer.invoke('dashboard:commit-pet-pack', payload),
  setActivePet: (id) => ipcRenderer.invoke('dashboard:set-active-pet', id),
  deletePetPack: (id) => ipcRenderer.invoke('dashboard:delete-pet-pack', id),
  setActionMapping: (status, row) => ipcRenderer.invoke('dashboard:set-action-mapping', { status, row }),
  getMemory: () => ipcRenderer.invoke('dashboard:get-memory'),
  deleteMemory: (id) => ipcRenderer.invoke('dashboard:delete-memory', id),
  clearMemory: () => ipcRenderer.invoke('dashboard:clear-memory'),
  addMemory: (fact) => ipcRenderer.invoke('dashboard:add-memory', fact),
  editMemory: (fact) => ipcRenderer.invoke('dashboard:edit-memory', fact),
  toggleScreenTips: (paused) => ipcRenderer.send('dashboard:toggle-screentips', paused),
  triggerScreenTip: () => ipcRenderer.invoke('dashboard:trigger-screentip'),
  askAboutEntry: (text) => ipcRenderer.send('dashboard:ask-about-entry', text),
  todoAdd: (text) => ipcRenderer.send('pet:todo-add', text),
  todoComplete: (id) => ipcRenderer.send('pet:todo-complete', id),
  todoRemove: (id) => ipcRenderer.send('pet:todo-remove', id),
  todoEdit: (fields) => ipcRenderer.send('pet:todo-edit', fields),
  taskJump: (sessionId) => ipcRenderer.send('pet:task-jump', sessionId),
  pomodoroStart: () => ipcRenderer.send('pet:pomodoro-start'),
  pomodoroStop: () => ipcRenderer.send('pet:pomodoro-stop'),
  outlookStatus: () => ipcRenderer.invoke('dashboard:outlook-status'),
  outlookSetClientId: (payload) => ipcRenderer.invoke('dashboard:outlook-set-client-id', payload),
  outlookConnect: () => ipcRenderer.invoke('dashboard:outlook-connect'),
  outlookDisconnect: () => ipcRenderer.invoke('dashboard:outlook-disconnect'),
  outlookSyncNow: () => ipcRenderer.invoke('dashboard:outlook-sync-now'),

  chatSend: (text) => ipcRenderer.send('pet:chat-send', text),
  chatGetHistory: () => ipcRenderer.invoke('dashboard:chat-get-history'),
  onChatDelta: (cb) => ipcRenderer.on('pet:chat-delta', (_e, data) => cb(data)),
  onChatMessageDone: (cb) => ipcRenderer.on('pet:chat-message-done', (_e, data) => cb(data)),
  onChatError: (cb) => ipcRenderer.on('pet:chat-error', (_e, data) => cb(data)),
  onChatSpeakDelta: (cb) => ipcRenderer.on('pet:chat-speak-delta', (_e, data) => cb(data)),
  onChatComplete: (cb) => ipcRenderer.on('pet:chat-complete', (_e, data) => cb(data)),
  voicePptStart: () => ipcRenderer.send('pet:voice-ppt-start'),
  voicePptStop: () => ipcRenderer.send('pet:voice-ppt-stop'),
  voiceCallModeToggle: () => ipcRenderer.send('pet:voice-call-mode-toggle'),
  onVoiceCallModeState: (cb) => ipcRenderer.on('pet:voice-call-mode-state', (_e, data) => cb(data)),
  onVoiceTranscript: (cb) => ipcRenderer.on('pet:voice-transcript', (_e, text) => cb(text)),
  onVoiceError: (cb) => ipcRenderer.on('pet:voice-error', (_e, data) => cb(data)),

  // Conversation history parity with the pet window's own chat panel --
  // same channels, main.js already replies to whichever window sent these.
  requestChatConvList: () => ipcRenderer.send('pet:chat-conv-list-request'),
  switchChatConv: (id) => ipcRenderer.send('pet:chat-conv-switch', id),
  newChatConv: () => ipcRenderer.send('pet:chat-conv-new'),
  deleteChatConv: (id) => ipcRenderer.send('pet:chat-conv-delete', id),
  onChatConvList: (cb) => ipcRenderer.on('pet:chat-conv-list', (_e, data) => cb(data)),
  onChatHistory: (cb) => ipcRenderer.on('pet:chat-history', (_e, data) => cb(data)),
  captureScreenshot: () => ipcRenderer.invoke('pet:capture-screenshot'),
  synthesizeSpeech: (text) => ipcRenderer.invoke('pet:synthesize-speech', text),
  synthesizeSong: (lyrics, voice) => ipcRenderer.invoke('pet:synthesize-song', { lyrics, voice }),
  chatSendWithImage: (text, imageBase64) => ipcRenderer.send('pet:chat-send-with-image', { text, imageBase64 }),
  transcribeSinging: (audioPath) => ipcRenderer.invoke('dashboard:transcribe-singing', audioPath),
  extractInstrumental: (audioPath) => ipcRenderer.invoke('dashboard:extract-instrumental', audioPath),
  pickVoiceModel: () => ipcRenderer.invoke('dashboard:pick-voice-model'),
  convertVoice: (payload) => ipcRenderer.invoke('dashboard:convert-voice', {
    audioPath: payload.audioPath,
    modelPath: payload.modelPath,
    indexPath: payload.indexPath,
    pitchShift: payload.pitchShift,
    indexRate: payload.indexRate,
    instrumentalPath: payload.instrumentalPath,
  }),
  saveVoiceModel: (payload) => ipcRenderer.invoke('dashboard:save-voice-model', payload),
  renameVoiceModel: (id, name) => ipcRenderer.invoke('dashboard:rename-voice-model', { id, name }),
  deleteVoiceModel: (id) => ipcRenderer.invoke('dashboard:delete-voice-model', { id }),
  setDefaultVoiceModel: (id) => ipcRenderer.invoke('dashboard:set-default-voice-model', { id }),
  listVocalHistory: () => ipcRenderer.invoke('dashboard:list-vocal-history'),
  deleteVocalHistoryEntry: (id) => ipcRenderer.invoke('dashboard:delete-vocal-history-entry', { id }),
  replayVocalHistoryEntry: (id) => ipcRenderer.invoke('dashboard:replay-vocal-history-entry', { id }),
  mixTracks: (payload) => ipcRenderer.invoke('dashboard:mix-tracks', payload),
  enhanceVocal: (payload) => ipcRenderer.invoke('dashboard:enhance-vocal', payload),
  listTestSongs: () => ipcRenderer.invoke('dashboard:list-test-songs'),
  // Electron 32+ dropped File.path for security; webUtils is the replacement
  // way to resolve a <input type=file> File object back to an absolute path.
  getPathForFile: (file) => webUtils.getPathForFile(file),
});
