// CommonJS on purpose: Electron preload scripts are not ES modules even when
// the package is "type": "module".
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pet', {
  getConfig: () => ipcRenderer.invoke('pet:config'),

  onCursor: (fn) => ipcRenderer.on('pet:cursor', (_e, d) => fn(d)),
  onSwitch: (fn) => ipcRenderer.on('pet:switch', (_e, d) => fn(d)),
  onMoving: (fn) => ipcRenderer.on('pet:moving', (_e, d) => fn(d)),
  onWanderArrived: (fn) => ipcRenderer.on('pet:wander-arrived', (_e, d) => fn(d)),
  onDragLanded: (fn) => ipcRenderer.on('pet:drag-landed', (_e, d) => fn(d)),
  onToggles: (fn) => ipcRenderer.on('pet:toggles', (_e, d) => fn(d)),
  onScale: (fn) => ipcRenderer.on('pet:scale', (_e, d) => fn(d)),
  onPlayRow: (fn) => ipcRenderer.on('pet:play-row', (_e, d) => fn(d)),
  onPlaySpin: (fn) => ipcRenderer.on('pet:play-spin', () => fn()),
  onClaudeStatus: (fn) => ipcRenderer.on('pet:claude-status', (_e, d) => fn(d)),
  onAiStatus: (fn) => ipcRenderer.on('pet:ai-status', (_e, d) => fn(d)),
  onContextUsage: (fn) => ipcRenderer.on('pet:context-usage', (_e, d) => fn(d)),
  onRateLimits: (fn) => ipcRenderer.on('pet:rate-limits', (_e, d) => fn(d)),
  onPermissionRequest: (fn) => ipcRenderer.on('pet:permission-request', (_e, d) => fn(d)),
  onPermissionResolved: (fn) => ipcRenderer.on('pet:permission-resolved', (_e, requestId) => fn(requestId)),
  onScreenTip: (fn) => ipcRenderer.on('pet:screen-tip', (_e, d) => fn(d)),
  onCameraFrameRequest: (fn) => ipcRenderer.on('pet:camera-frame-request', (_e, d) => fn(d)),
  sendCameraFrameResponse: (payload) => ipcRenderer.send('pet:camera-frame-response', payload),
  voicePptStart: () => ipcRenderer.send('pet:voice-ppt-start'),
  voicePptStop: () => ipcRenderer.send('pet:voice-ppt-stop'),
  voiceCallModeToggle: () => ipcRenderer.send('pet:voice-call-mode-toggle'),
  onVoiceTranscript: (fn) => ipcRenderer.on('pet:voice-transcript', (_e, text) => fn(text)),
  onVoiceCallModeState: (fn) => ipcRenderer.on('pet:voice-call-mode-state', (_e, d) => fn(d)),
  onVoiceError: (fn) => ipcRenderer.on('pet:voice-error', (_e, d) => fn(d)),
  onVoiceConfig: (fn) => ipcRenderer.on('pet:voice-config', (_e, v) => fn(v)),
  onReplyBoxCloseForced: (fn) => ipcRenderer.on('pet:reply-box-close-forced', () => fn()),
  onBubbleLayout: (fn) => ipcRenderer.on('pet:bubble-layout', (_e, d) => fn(d)),
  onBeat: (fn) => ipcRenderer.on('pet:beat', (_e, d) => fn(d)),
  onMusicComment: (fn) => ipcRenderer.on('pet:music-comment', (_e, d) => fn(d)),
  onUnseenCompletion: (fn) => ipcRenderer.on('pet:unseen-completion', (_e, d) => fn(d)),
  onPomodoroState: (fn) => ipcRenderer.on('pet:pomodoro-state', (_e, d) => fn(d)),
  onPomodoroDone: (fn) => ipcRenderer.on('pet:pomodoro-done', () => fn()),
  onChatPanelReady: (fn) => ipcRenderer.on('pet:chat-panel-ready', (_e, d) => fn(d)),
  onChatPanelClosed: (fn) => ipcRenderer.on('pet:chat-panel-closed', () => fn()),
  onChatHistory: (fn) => ipcRenderer.on('pet:chat-history', (_e, d) => fn(d)),
  onChatDelta: (fn) => ipcRenderer.on('pet:chat-delta', (_e, d) => fn(d)),
  onChatMessageDone: (fn) => ipcRenderer.on('pet:chat-message-done', (_e, d) => fn(d)),
  onChatError: (fn) => ipcRenderer.on('pet:chat-error', (_e, d) => fn(d)),
  onChatReply: (fn) => ipcRenderer.on('pet:chat-reply', (_e, d) => fn(d)),
  onChatSpeak: (fn) => ipcRenderer.on('pet:chat-speak-delta', (_e, d) => fn(d)),
  onChatComplete: (fn) => ipcRenderer.on('pet:chat-complete', (_e, d) => fn(d)),
  onChatEmotion: (fn) => ipcRenderer.on('pet:chat-emotion', (_e, d) => fn(d)),
  onChatConvList: (fn) => ipcRenderer.on('pet:chat-conv-list', (_e, d) => fn(d)),
  onTodos: (fn) => ipcRenderer.on('pet:todos', (_e, d) => fn(d)),
  onTodoPanelReady: (fn) => ipcRenderer.on('pet:todo-panel-ready', (_e, d) => fn(d)),
  onTodoPanelClosed: (fn) => ipcRenderer.on('pet:todo-panel-closed', () => fn()),
  onReportResult: (fn) => ipcRenderer.on('pet:report-result', (_e, d) => fn(d)),
  onTaskListResult: (fn) => ipcRenderer.on('pet:task-list-result', (_e, d) => fn(d)),
  onToolbarReady: (fn) => ipcRenderer.on('pet:toolbar-ready', (_e, d) => fn(d)),
  onToolbarClosed: (fn) => ipcRenderer.on('pet:toolbar-closed', () => fn()),
  onToolbarState: (fn) => ipcRenderer.on('pet:toolbar-state', (_e, d) => fn(d)),
  onSleepSettings: (fn) => ipcRenderer.on('pet:sleep-settings', (_e, d) => fn(d)),
  onStatusLightsEnabled: (fn) => ipcRenderer.on('pet:status-lights-enabled', (_e, v) => fn(v)),
  onContextRingEnabled: (fn) => ipcRenderer.on('pet:context-ring-enabled', (_e, v) => fn(v)),
  onSkinColor: (fn) => ipcRenderer.on('pet:skin-color', (_e, v) => fn(v)),
  onAccentColor: (fn) => ipcRenderer.on('pet:accent-color', (_e, v) => fn(v)),
  onTextColor: (fn) => ipcRenderer.on('pet:text-color', (_e, v) => fn(v)),
  onAssistantBubbleColor: (fn) => ipcRenderer.on('pet:assistant-bubble-color', (_e, v) => fn(v)),
  onThemePreset: (fn) => ipcRenderer.on('pet:theme-preset', (_e, v) => fn(v)),
  onUiScale: (fn) => ipcRenderer.on('pet:ui-scale', (_e, v) => fn(v)),
  onTipDisplayMode: (fn) => ipcRenderer.on('pet:tip-display-mode', (_e, v) => fn(v)),
  onSoundsEnabled: (fn) => ipcRenderer.on('pet:sounds-enabled', (_e, v) => fn(v)),
  onSoundsFilesChanged: (fn) => ipcRenderer.on('pet:sounds-files-changed', (_e, d) => fn(d)),
  onGesturesChanged: (fn) => ipcRenderer.on('pet:gestures-changed', (_e, d) => fn(d)),
  onScreentipHistoryResult: (fn) => ipcRenderer.on('pet:screentip-history-result', (_e, d) => fn(d)),
  onScreentipSummaryResult: (fn) => ipcRenderer.on('pet:screentip-summary-result', (_e, d) => fn(d)),
  onChatPrefill: (fn) => ipcRenderer.on('pet:chat-prefill', (_e, d) => fn(d)),

  setInteractive: (hit) => ipcRenderer.send('pet:interactive', hit),
  bubbleSpace: (needed) => ipcRenderer.send('pet:bubble-space', { needed }),
  wanderStart: (opts) => ipcRenderer.send('pet:wander-start', opts),
  dragStart: () => ipcRenderer.send('pet:drag-start'),
  dragEnd: () => ipcRenderer.send('pet:drag-end'),
  contextMenu: () => ipcRenderer.send('pet:context-menu'),
  activateClaudeWindow: () => ipcRenderer.send('pet:activate-claude'),
  closeChatPanel: () => ipcRenderer.send('pet:chat-panel-close'),
  chatSend: (text) => ipcRenderer.send('pet:chat-send', text),
  requestChatConvList: () => ipcRenderer.send('pet:chat-conv-list-request'),
  switchChatConv: (id) => ipcRenderer.send('pet:chat-conv-switch', id),
  newChatConv: () => ipcRenderer.send('pet:chat-conv-new'),
  deleteChatConv: (id) => ipcRenderer.send('pet:chat-conv-delete', id),
  todoAdd: (text) => ipcRenderer.send('pet:todo-add', text),
  todoComplete: (id) => ipcRenderer.send('pet:todo-complete', id),
  todoRemove: (id) => ipcRenderer.send('pet:todo-remove', id),
  todoEdit: (fields) => ipcRenderer.send('pet:todo-edit', fields),
  closeTodoPanel: () => ipcRenderer.send('pet:todo-panel-close'),
  requestReport: (kind) => ipcRenderer.send('pet:report-request', kind),
  getReports: () => ipcRenderer.invoke('pet:get-reports'),
  deleteReport: (id) => ipcRenderer.invoke('pet:delete-report', id),
  requestTaskList: () => ipcRenderer.send('pet:task-list-request'),
  taskJump: (sessionId) => ipcRenderer.send('pet:task-jump', sessionId),
  openToolbar: () => ipcRenderer.send('pet:toolbar-open'),
  toolbarClose: () => ipcRenderer.send('pet:toolbar-close'),
  toolbarAction: (action) => ipcRenderer.send('pet:toolbar-action', action),
  toolbarToggle: (toggle) => ipcRenderer.send('pet:toolbar-toggle', toggle),
  requestScreenTipHistory: (day) => ipcRenderer.send('pet:screentip-history-request', day),
  requestScreenTipSummary: (day) => ipcRenderer.send('pet:screentip-summary-request', day),
  askAboutEntry: (text) => ipcRenderer.send('pet:ask-about-entry', text),
  captureScreenshot: () => ipcRenderer.invoke('pet:capture-screenshot'),
  chatSendWithImage: (text, imageBase64) => ipcRenderer.send('pet:chat-send-with-image', { text, imageBase64 }),
  synthesizeSpeech: (text) => ipcRenderer.invoke('pet:synthesize-speech', text),
  fatal: (msg) => ipcRenderer.send('pet:fatal', msg),
  permissionResponse: (requestId, decision) => ipcRenderer.send('pet:permission-response', { requestId, decision }),
});
